version: '3.8'

services:
  evaluation:
    build: .
#    command: tail -f /dev/null
    environment:
      - EVAL_MODE=test
      - PYTHONPATH=/build
    networks:
      - shared-hma-network
  
# hma needs to be on same docker network 
networks:
  shared-hma-network:
    external: true
